name: CI
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read 

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - run: 'go test -v ./...'

